image: node:latest

stages:
    - build
    - test
    - deploy

compile:
    stage: build
    script:
        - yarn install

eslint:
    stage: test
    script:
        - yarn install
        - yarn lint

deploy-staging:
    stage: deploy
    image: ruby:latest
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - develop

deploy-production:
    stage: deploy
    image: ruby:latest
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master
